; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules

projects[views_bulk_operations][version] = "3.1"

projects[admin_menu][version] = "3.0-rc4"

projects[adminimal_admin_menu][version] = "1.0+1-dev"

projects[ctools][version] = "1.3"

projects[devel][version] = "1.3"

projects[diff][version] = "3.2"

projects[entity][version] = "1.1"

projects[environment_indicator][version] = "1.1"

projects[features][version] = "2.0-rc1"

projects[field_group][version] = "1.1"

projects[media][version] = "1.3"

projects[fpa][version] = "2.3"

projects[menu_block][version] = "2.3"

projects[module_filter][version] = "1.7"

projects[panels][version] = "3.3"

projects[pathauto][version] = "1.2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[spry_admin_ui][download][type] = "git"
projects[spry_admin_ui][download][url] = "git@github.com:SpryDigital/SpryDrupalAdminUI.git"
projects[spry_admin_ui][type] = "module"
projects[spry_admin_ui][version] = "1.0"

projects[token][version] = "1.5"

projects[views][version] = "3.7"

; Themes
projects[adminimal_theme][version] = "1.x-dev"


